#include <colab/protocol/get_config.hpp>
#include <colab/protocol/config.hpp>
#include <colab/protocol/asset.hpp>
#include <colab/protocol/types.hpp>
#include <colab/protocol/version.hpp>

namespace colab { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_NET
   result[ "IS_TEST_NET" ] = true;
   result["TESTNET_BLOCK_LIMIT"] = TESTNET_BLOCK_LIMIT;
#else
   result[ "IS_TEST_NET" ] = false;
#endif
#ifdef COLAB_ENABLE_SMT
   result[ "COLAB_ENABLE_SMT" ] = true;
   result["SMT_VESTING_WITHDRAW_INTERVAL_SECONDS"] = SMT_VESTING_WITHDRAW_INTERVAL_SECONDS;
   result["SMT_UPVOTE_LOCKOUT"] = SMT_UPVOTE_LOCKOUT;
   result["SMT_MAX_VOTABLE_ASSETS"] = SMT_MAX_VOTABLE_ASSETS;
#else
   result[ "COLAB_ENABLE_SMT" ] = false;
#endif

   result["SBD_SYMBOL"] = SBD_SYMBOL;
   result["COLAB_INITIAL_VOTE_POWER_RATE"] = COLAB_INITIAL_VOTE_POWER_RATE;
   result["COLAB_REDUCED_VOTE_POWER_RATE"] = COLAB_REDUCED_VOTE_POWER_RATE;
   result["COLAB_100_PERCENT"] = COLAB_100_PERCENT;
   result["COLAB_1_PERCENT"] = COLAB_1_PERCENT;
   result["COLAB_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = COLAB_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["COLAB_ACTIVE_CHALLENGE_COOLDOWN"] = COLAB_ACTIVE_CHALLENGE_COOLDOWN;
   result["COLAB_ACTIVE_CHALLENGE_FEE"] = COLAB_ACTIVE_CHALLENGE_FEE;
   result["COLAB_ADDRESS_PREFIX"] = COLAB_ADDRESS_PREFIX;
   result["COLAB_APR_PERCENT_MULTIPLY_PER_BLOCK"] = COLAB_APR_PERCENT_MULTIPLY_PER_BLOCK;
   result["COLAB_APR_PERCENT_MULTIPLY_PER_HOUR"] = COLAB_APR_PERCENT_MULTIPLY_PER_HOUR;
   result["COLAB_APR_PERCENT_MULTIPLY_PER_ROUND"] = COLAB_APR_PERCENT_MULTIPLY_PER_ROUND;
   result["COLAB_APR_PERCENT_SHIFT_PER_BLOCK"] = COLAB_APR_PERCENT_SHIFT_PER_BLOCK;
   result["COLAB_APR_PERCENT_SHIFT_PER_HOUR"] = COLAB_APR_PERCENT_SHIFT_PER_HOUR;
   result["COLAB_APR_PERCENT_SHIFT_PER_ROUND"] = COLAB_APR_PERCENT_SHIFT_PER_ROUND;
   result["COLAB_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = COLAB_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["COLAB_BANDWIDTH_PRECISION"] = COLAB_BANDWIDTH_PRECISION;
   result["COLAB_BLOCKCHAIN_PRECISION"] = COLAB_BLOCKCHAIN_PRECISION;
   result["COLAB_BLOCKCHAIN_PRECISION_DIGITS"] = COLAB_BLOCKCHAIN_PRECISION_DIGITS;
   result["COLAB_BLOCKCHAIN_HARDFORK_VERSION"] = COLAB_BLOCKCHAIN_HARDFORK_VERSION;
   result["COLAB_BLOCKCHAIN_VERSION"] = COLAB_BLOCKCHAIN_VERSION;
   result["COLAB_BLOCK_INTERVAL"] = COLAB_BLOCK_INTERVAL;
   result["COLAB_BLOCKS_PER_DAY"] = COLAB_BLOCKS_PER_DAY;
   result["COLAB_BLOCKS_PER_HOUR"] = COLAB_BLOCKS_PER_HOUR;
   result["COLAB_BLOCKS_PER_YEAR"] = COLAB_BLOCKS_PER_YEAR;
   result["COLAB_CASHOUT_WINDOW_SECONDS"] = COLAB_CASHOUT_WINDOW_SECONDS;
   result["COLAB_CASHOUT_WINDOW_SECONDS_PRE_HF12"] = COLAB_CASHOUT_WINDOW_SECONDS_PRE_HF12;
   result["COLAB_CASHOUT_WINDOW_SECONDS_PRE_HF17"] = COLAB_CASHOUT_WINDOW_SECONDS_PRE_HF17;
   result["COLAB_CHAIN_ID"] = COLAB_CHAIN_ID;
   result["COLAB_COMMENT_REWARD_FUND_NAME"] = COLAB_COMMENT_REWARD_FUND_NAME;
   result["COLAB_CONTENT_APR_PERCENT"] = COLAB_CONTENT_APR_PERCENT;
   result["COLAB_CONTENT_CONSTANT_HF0"] = COLAB_CONTENT_CONSTANT_HF0;
   result["COLAB_CONTENT_REWARD_PERCENT"] = COLAB_CONTENT_REWARD_PERCENT;
   result["COLAB_CONVERSION_DELAY"] = COLAB_CONVERSION_DELAY;
   result["COLAB_CONVERSION_DELAY_PRE_HF_16"] = COLAB_CONVERSION_DELAY_PRE_HF_16;
   result["COLAB_CREATE_ACCOUNT_DELEGATION_RATIO"] = COLAB_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["COLAB_CREATE_ACCOUNT_DELEGATION_TIME"] = COLAB_CREATE_ACCOUNT_DELEGATION_TIME;
   result["COLAB_CREATE_ACCOUNT_WITH_COLAB_MODIFIER"] = COLAB_CREATE_ACCOUNT_WITH_COLAB_MODIFIER;
   result["COLAB_CURATE_APR_PERCENT"] = COLAB_CURATE_APR_PERCENT;
   result["COLAB_DEFAULT_SBD_INTEREST_RATE"] = COLAB_DEFAULT_SBD_INTEREST_RATE;
   result["COLAB_EQUIHASH_K"] = COLAB_EQUIHASH_K;
   result["COLAB_EQUIHASH_N"] = COLAB_EQUIHASH_N;
   result["COLAB_FEED_HISTORY_WINDOW"] = COLAB_FEED_HISTORY_WINDOW;
   result["COLAB_FEED_HISTORY_WINDOW_PRE_HF_16"] = COLAB_FEED_HISTORY_WINDOW_PRE_HF_16;
   result["COLAB_FEED_INTERVAL_BLOCKS"] = COLAB_FEED_INTERVAL_BLOCKS;
   result["COLAB_GENESIS_TIME"] = COLAB_GENESIS_TIME;
   result["COLAB_HARDFORK_REQUIRED_WITNESSES"] = COLAB_HARDFORK_REQUIRED_WITNESSES;
   result["COLAB_INFLATION_NARROWING_PERIOD"] = COLAB_INFLATION_NARROWING_PERIOD;
   result["COLAB_INFLATION_RATE_START_PERCENT"] = COLAB_INFLATION_RATE_START_PERCENT;
   result["COLAB_INFLATION_RATE_STOP_PERCENT"] = COLAB_INFLATION_RATE_STOP_PERCENT;
   result["COLAB_INIT_MINER_NAME"] = COLAB_INIT_MINER_NAME;
   result["COLAB_INIT_PUBLIC_KEY_STR"] = COLAB_INIT_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["COLAB_INIT_PRIVATE_KEY"] = COLAB_INIT_PRIVATE_KEY;
#endif
   result["COLAB_INIT_SUPPLY"] = COLAB_INIT_SUPPLY;
   result["COLAB_INIT_TIME"] = COLAB_INIT_TIME;
   result["COLAB_IRREVERSIBLE_THRESHOLD"] = COLAB_IRREVERSIBLE_THRESHOLD;
   result["COLAB_LIQUIDITY_APR_PERCENT"] = COLAB_LIQUIDITY_APR_PERCENT;
   result["COLAB_LIQUIDITY_REWARD_BLOCKS"] = COLAB_LIQUIDITY_REWARD_BLOCKS;
   result["COLAB_LIQUIDITY_REWARD_PERIOD_SEC"] = COLAB_LIQUIDITY_REWARD_PERIOD_SEC;
   result["COLAB_LIQUIDITY_TIMEOUT_SEC"] = COLAB_LIQUIDITY_TIMEOUT_SEC;
   result["COLAB_MAX_ACCOUNT_CREATION_FEE"] = COLAB_MAX_ACCOUNT_CREATION_FEE;
   result["COLAB_MAX_ACCOUNT_NAME_LENGTH"] = COLAB_MAX_ACCOUNT_NAME_LENGTH;
   result["COLAB_MAX_ACCOUNT_WITNESS_VOTES"] = COLAB_MAX_ACCOUNT_WITNESS_VOTES;
   result["COLAB_MAX_ASSET_WHITELIST_AUTHORITIES"] = COLAB_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["COLAB_MAX_AUTHORITY_MEMBERSHIP"] = COLAB_MAX_AUTHORITY_MEMBERSHIP;
   result["COLAB_MAX_BLOCK_SIZE"] = COLAB_MAX_BLOCK_SIZE;
   result["COLAB_SOFT_MAX_BLOCK_SIZE"] = COLAB_SOFT_MAX_BLOCK_SIZE;
   result["COLAB_MAX_CASHOUT_WINDOW_SECONDS"] = COLAB_MAX_CASHOUT_WINDOW_SECONDS;
   result["COLAB_MAX_COMMENT_DEPTH"] = COLAB_MAX_COMMENT_DEPTH;
   result["COLAB_MAX_COMMENT_DEPTH_PRE_HF17"] = COLAB_MAX_COMMENT_DEPTH_PRE_HF17;
   result["COLAB_MAX_FEED_AGE_SECONDS"] = COLAB_MAX_FEED_AGE_SECONDS;
   result["COLAB_MAX_INSTANCE_ID"] = COLAB_MAX_INSTANCE_ID;
   result["COLAB_MAX_MEMO_SIZE"] = COLAB_MAX_MEMO_SIZE;
   result["COLAB_MAX_WITNESSES"] = COLAB_MAX_WITNESSES;
   result["COLAB_MAX_MINER_WITNESSES_HF0"] = COLAB_MAX_MINER_WITNESSES_HF0;
   result["COLAB_MAX_MINER_WITNESSES_HF17"] = COLAB_MAX_MINER_WITNESSES_HF17;
   result["COLAB_MAX_PERMLINK_LENGTH"] = COLAB_MAX_PERMLINK_LENGTH;
   result["COLAB_MAX_PROXY_RECURSION_DEPTH"] = COLAB_MAX_PROXY_RECURSION_DEPTH;
   result["COLAB_MAX_RATION_DECAY_RATE"] = COLAB_MAX_RATION_DECAY_RATE;
   result["COLAB_MAX_RESERVE_RATIO"] = COLAB_MAX_RESERVE_RATIO;
   result["COLAB_MAX_RUNNER_WITNESSES_HF0"] = COLAB_MAX_RUNNER_WITNESSES_HF0;
   result["COLAB_MAX_RUNNER_WITNESSES_HF17"] = COLAB_MAX_RUNNER_WITNESSES_HF17;
   result["COLAB_MAX_SATOSHIS"] = COLAB_MAX_SATOSHIS;
   result["COLAB_MAX_SHARE_SUPPLY"] = COLAB_MAX_SHARE_SUPPLY;
   result["COLAB_MAX_SIG_CHECK_DEPTH"] = COLAB_MAX_SIG_CHECK_DEPTH;
   result["COLAB_MAX_SIG_CHECK_ACCOUNTS"] = COLAB_MAX_SIG_CHECK_ACCOUNTS;
   result["COLAB_MAX_TIME_UNTIL_EXPIRATION"] = COLAB_MAX_TIME_UNTIL_EXPIRATION;
   result["COLAB_MAX_TRANSACTION_SIZE"] = COLAB_MAX_TRANSACTION_SIZE;
   result["COLAB_MAX_UNDO_HISTORY"] = COLAB_MAX_UNDO_HISTORY;
   result["COLAB_MAX_URL_LENGTH"] = COLAB_MAX_URL_LENGTH;
   result["COLAB_MAX_VOTE_CHANGES"] = COLAB_MAX_VOTE_CHANGES;
   result["COLAB_MAX_VOTED_WITNESSES_HF0"] = COLAB_MAX_VOTED_WITNESSES_HF0;
   result["COLAB_MAX_VOTED_WITNESSES_HF17"] = COLAB_MAX_VOTED_WITNESSES_HF17;
   result["COLAB_MAX_WITHDRAW_ROUTES"] = COLAB_MAX_WITHDRAW_ROUTES;
   result["COLAB_MAX_WITNESS_URL_LENGTH"] = COLAB_MAX_WITNESS_URL_LENGTH;
   result["COLAB_MIN_ACCOUNT_CREATION_FEE"] = COLAB_MIN_ACCOUNT_CREATION_FEE;
   result["COLAB_MIN_ACCOUNT_NAME_LENGTH"] = COLAB_MIN_ACCOUNT_NAME_LENGTH;
   result["COLAB_MIN_BLOCK_SIZE_LIMIT"] = COLAB_MIN_BLOCK_SIZE_LIMIT;
   result["COLAB_MIN_BLOCK_SIZE"] = COLAB_MIN_BLOCK_SIZE;
   result["COLAB_MIN_CONTENT_REWARD"] = COLAB_MIN_CONTENT_REWARD;
   result["COLAB_MIN_CURATE_REWARD"] = COLAB_MIN_CURATE_REWARD;
   result["COLAB_MIN_PERMLINK_LENGTH"] = COLAB_MIN_PERMLINK_LENGTH;
   result["COLAB_MIN_REPLY_INTERVAL"] = COLAB_MIN_REPLY_INTERVAL;
   result["COLAB_MIN_REPLY_INTERVAL_HF20"] = COLAB_MIN_REPLY_INTERVAL_HF20;
   result["COLAB_MIN_ROOT_COMMENT_INTERVAL"] = COLAB_MIN_ROOT_COMMENT_INTERVAL;
   result["COLAB_MIN_VOTE_INTERVAL_SEC"] = COLAB_MIN_VOTE_INTERVAL_SEC;
   result["COLAB_MINER_ACCOUNT"] = COLAB_MINER_ACCOUNT;
   result["COLAB_MINER_PAY_PERCENT"] = COLAB_MINER_PAY_PERCENT;
   result["COLAB_MIN_FEEDS"] = COLAB_MIN_FEEDS;
   result["COLAB_MINING_REWARD"] = COLAB_MINING_REWARD;
   result["COLAB_MINING_TIME"] = COLAB_MINING_TIME;
   result["COLAB_MIN_LIQUIDITY_REWARD"] = COLAB_MIN_LIQUIDITY_REWARD;
   result["COLAB_MIN_LIQUIDITY_REWARD_PERIOD_SEC"] = COLAB_MIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["COLAB_MIN_PAYOUT_SBD"] = COLAB_MIN_PAYOUT_SBD;
   result["COLAB_MIN_POW_REWARD"] = COLAB_MIN_POW_REWARD;
   result["COLAB_MIN_PRODUCER_REWARD"] = COLAB_MIN_PRODUCER_REWARD;
   result["COLAB_MIN_TRANSACTION_EXPIRATION_LIMIT"] = COLAB_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["COLAB_MIN_TRANSACTION_SIZE_LIMIT"] = COLAB_MIN_TRANSACTION_SIZE_LIMIT;
   result["COLAB_MIN_UNDO_HISTORY"] = COLAB_MIN_UNDO_HISTORY;
   result["COLAB_NULL_ACCOUNT"] = COLAB_NULL_ACCOUNT;
   result["COLAB_NUM_INIT_MINERS"] = COLAB_NUM_INIT_MINERS;
   result["COLAB_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = COLAB_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["COLAB_OWNER_AUTH_RECOVERY_PERIOD"] = COLAB_OWNER_AUTH_RECOVERY_PERIOD;
   result["COLAB_OWNER_CHALLENGE_COOLDOWN"] = COLAB_OWNER_CHALLENGE_COOLDOWN;
   result["COLAB_OWNER_CHALLENGE_FEE"] = COLAB_OWNER_CHALLENGE_FEE;
   result["COLAB_OWNER_UPDATE_LIMIT"] = COLAB_OWNER_UPDATE_LIMIT;
   result["COLAB_POST_AVERAGE_WINDOW"] = COLAB_POST_AVERAGE_WINDOW;
   result["COLAB_POST_REWARD_FUND_NAME"] = COLAB_POST_REWARD_FUND_NAME;
   result["COLAB_POST_WEIGHT_CONSTANT"] = COLAB_POST_WEIGHT_CONSTANT;
   result["COLAB_POW_APR_PERCENT"] = COLAB_POW_APR_PERCENT;
   result["COLAB_PRODUCER_APR_PERCENT"] = COLAB_PRODUCER_APR_PERCENT;
   result["COLAB_PROXY_TO_SELF_ACCOUNT"] = COLAB_PROXY_TO_SELF_ACCOUNT;
   result["COLAB_SBD_INTEREST_COMPOUND_INTERVAL_SEC"] = COLAB_SBD_INTEREST_COMPOUND_INTERVAL_SEC;
   result["COLAB_SECONDS_PER_YEAR"] = COLAB_SECONDS_PER_YEAR;
   result["COLAB_RECENT_RSHARES_DECAY_TIME_HF19"] = COLAB_RECENT_RSHARES_DECAY_TIME_HF19;
   result["COLAB_RECENT_RSHARES_DECAY_TIME_HF17"] = COLAB_RECENT_RSHARES_DECAY_TIME_HF17;
   result["COLAB_REVERSE_AUCTION_WINDOW_SECONDS_HF6"] = COLAB_REVERSE_AUCTION_WINDOW_SECONDS_HF6;
   result["COLAB_REVERSE_AUCTION_WINDOW_SECONDS_HF20"] = COLAB_REVERSE_AUCTION_WINDOW_SECONDS_HF20;
   result["COLAB_ROOT_POST_PARENT"] = COLAB_ROOT_POST_PARENT;
   result["COLAB_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = COLAB_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["COLAB_SAVINGS_WITHDRAW_TIME"] = COLAB_SAVINGS_WITHDRAW_TIME;
   result["COLAB_SBD_START_PERCENT_HF14"] = COLAB_SBD_START_PERCENT_HF14;
   result["COLAB_SBD_START_PERCENT_HF20"] = COLAB_SBD_START_PERCENT_HF20;
   result["COLAB_SBD_STOP_PERCENT_HF14"] = COLAB_SBD_STOP_PERCENT_HF14;
   result["COLAB_SBD_STOP_PERCENT_HF20"] = COLAB_SBD_STOP_PERCENT_HF20;
   result["COLAB_SECOND_CASHOUT_WINDOW"] = COLAB_SECOND_CASHOUT_WINDOW;
   result["COLAB_SOFT_MAX_COMMENT_DEPTH"] = COLAB_SOFT_MAX_COMMENT_DEPTH;
   result["COLAB_START_MINER_VOTING_BLOCK"] = COLAB_START_MINER_VOTING_BLOCK;
   result["COLAB_START_VESTING_BLOCK"] = COLAB_START_VESTING_BLOCK;
   result["COLAB_TEMP_ACCOUNT"] = COLAB_TEMP_ACCOUNT;
   result["COLAB_UPVOTE_LOCKOUT_HF7"] = COLAB_UPVOTE_LOCKOUT_HF7;
   result["COLAB_UPVOTE_LOCKOUT_HF17"] = COLAB_UPVOTE_LOCKOUT_HF17;
   result["COLAB_UPVOTE_LOCKOUT_SECONDS"] = COLAB_UPVOTE_LOCKOUT_SECONDS;
   result["COLAB_VESTING_FUND_PERCENT"] = COLAB_VESTING_FUND_PERCENT;
   result["COLAB_VESTING_WITHDRAW_INTERVALS"] = COLAB_VESTING_WITHDRAW_INTERVALS;
   result["COLAB_VESTING_WITHDRAW_INTERVALS_PRE_HF_16"] = COLAB_VESTING_WITHDRAW_INTERVALS_PRE_HF_16;
   result["COLAB_VESTING_WITHDRAW_INTERVAL_SECONDS"] = COLAB_VESTING_WITHDRAW_INTERVAL_SECONDS;
   result["COLAB_VOTE_DUST_THRESHOLD"] = COLAB_VOTE_DUST_THRESHOLD;
   result["COLAB_VOTING_MANA_REGENERATION_SECONDS"] = COLAB_VOTING_MANA_REGENERATION_SECONDS;
   result["CLC_SYMBOL"] = CLC_SYMBOL;
   result["VESTS_SYMBOL"] = VESTS_SYMBOL;
   result["COLAB_VIRTUAL_SCHEDULE_LAP_LENGTH"] = COLAB_VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["COLAB_VIRTUAL_SCHEDULE_LAP_LENGTH2"] = COLAB_VIRTUAL_SCHEDULE_LAP_LENGTH2;
   result["COLAB_MAX_LIMIT_ORDER_EXPIRATION"] = COLAB_MAX_LIMIT_ORDER_EXPIRATION;
   result["COLAB_DELEGATION_RETURN_PERIOD_HF0"] = COLAB_DELEGATION_RETURN_PERIOD_HF0;
   result["COLAB_DELEGATION_RETURN_PERIOD_HF20"] = COLAB_DELEGATION_RETURN_PERIOD_HF20;
   result["COLAB_RD_MIN_DECAY_BITS"] = COLAB_RD_MIN_DECAY_BITS;
   result["COLAB_RD_MAX_DECAY_BITS"] = COLAB_RD_MAX_DECAY_BITS;
   result["COLAB_RD_DECAY_DENOM_SHIFT"] = COLAB_RD_DECAY_DENOM_SHIFT;
   result["COLAB_RD_MAX_POOL_BITS"] = COLAB_RD_MAX_POOL_BITS;
   result["COLAB_RD_MAX_BUDGET_1"] = COLAB_RD_MAX_BUDGET_1;
   result["COLAB_RD_MAX_BUDGET_2"] = COLAB_RD_MAX_BUDGET_2;
   result["COLAB_RD_MAX_BUDGET_3"] = COLAB_RD_MAX_BUDGET_3;
   result["COLAB_RD_MAX_BUDGET"] = COLAB_RD_MAX_BUDGET;
   result["COLAB_RD_MIN_DECAY"] = COLAB_RD_MIN_DECAY;
   result["COLAB_RD_MIN_BUDGET"] = COLAB_RD_MIN_BUDGET;
   result["COLAB_RD_MAX_DECAY"] = COLAB_RD_MAX_DECAY;
   result["COLAB_ACCOUNT_SUBSIDY_PRECISION"] = COLAB_ACCOUNT_SUBSIDY_PRECISION;
   result["COLAB_WITNESS_SUBSIDY_BUDGET_PERCENT"] = COLAB_WITNESS_SUBSIDY_BUDGET_PERCENT;
   result["COLAB_WITNESS_SUBSIDY_DECAY_PERCENT"] = COLAB_WITNESS_SUBSIDY_DECAY_PERCENT;
   result["COLAB_DEFAULT_ACCOUNT_SUBSIDY_DECAY"] = COLAB_DEFAULT_ACCOUNT_SUBSIDY_DECAY;
   result["COLAB_DEFAULT_ACCOUNT_SUBSIDY_BUDGET"] = COLAB_DEFAULT_ACCOUNT_SUBSIDY_BUDGET;
   result["COLAB_DECAY_BACKSTOP_PERCENT"] = COLAB_DECAY_BACKSTOP_PERCENT;

   return result;
}

} } // colab::protocol
